services:
    _defaults:
        autoconfigure: true
        autowire: true
    Flowd\Look\:
        resource: '../Classes/*'
        # value object, not a service
        exclude: '../Classes/Asset/IsolatedRendering.php'
